package com.reisparadijs.reisparadijs.business.domain;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/*********************************************
 * @Author Mirre Cicilia
 * @Studentennummer 500241293
 * @Project reisparadijs
 * @Created 07 August Wednesday 2024 - 17:23
 * @Korte beschrijving: /**
 * De Accommodation klasse vertegenwoordigt een accommodatie "blauwdruk" in het systeem.
 * Zijn attributen omvatten onder andere: id, postcode, huisnummer, titel, omschrijving, prijs per dag, type
 * accommodatie en parklocatie. Tot slot biedt Accommodation een methoden om de kenmerken te beheren en een
 * leesbare weergave te genereren via de toString().
 **********************************************/
public class Accommodation {

    private static final Logger logger = LoggerFactory.getLogger(Accommodation.class);

    private int id;
    private String zipCode;
    private String houseNumber;
    private String title;
    private String description;
    private double pricePerDay;
    private int numberOfGuests;
    private int numberOfBedrooms;
    private int numberOfBathrooms;
    private int numberOfBeds;
    private LocalDateTime publishedAt;
    private Boolean isActive = true; // default waarde
    private AppUser host;
    private AccommodationType accommodationType;
    private ParkLocation parkLocationId;
    private List<Image> imageList = new ArrayList<>();


    public Accommodation(int id, String zipCode, String houseNumber, String title, String description,
                         double pricePerDay, int numberOfGuests, int numberOfBedrooms, int numberOfBathrooms,
                         int numberOfBeds, LocalDateTime publishedAt, Boolean isActive, AppUser host,
                         AccommodationType accommodationType, ParkLocation parkLocationId, List<Image> imageList) {
        this.id = 0; // placeholder - id is autogenerated in workbench
        this.zipCode = zipCode;
        this.houseNumber = houseNumber;
        this.title = title;
        this.description = description;
        this.pricePerDay = pricePerDay;
        this.numberOfGuests = numberOfGuests;
        this.numberOfBedrooms = numberOfBedrooms;
        this.numberOfBathrooms = numberOfBathrooms;
        this.numberOfBeds = numberOfBeds;
        this.publishedAt = publishedAt;
        this.isActive = isActive;
        this.host = host;
        this.accommodationType = accommodationType;
        this.parkLocationId = parkLocationId;
        this.imageList = imageList;
        logger.info("New Accommodation created with all args with the title: '{}'.", title);
    }

    public Accommodation(int id, String zipCode, String houseNumber, String title, String description,
                         double pricePerDay, int numberOfGuests, int numberOfBedrooms, int numberOfBathrooms,
                         int numberOfBeds, LocalDateTime publishedAt, Boolean isActive, AppUser host,
                         AccommodationType accommodationType, ParkLocation parkLocationId) {
        this(id, zipCode, houseNumber, title, description, pricePerDay, numberOfGuests, numberOfBedrooms,
                numberOfBathrooms, numberOfBeds, publishedAt, isActive, host, accommodationType, parkLocationId,
                null);
        logger.info("New Accommodation created with the title: {}- without image list.", title);
    }

    public Accommodation(int id, String zipCode, String houseNumber, String title, String description,
                         double pricePerDay, int numberOfGuests, int numberOfBedrooms, int numberOfBathrooms,
                         int numberOfBeds, LocalDateTime publishedAt, Boolean isActive, AppUser host,
                         AccommodationType accommodationType) {
        this(id, zipCode, houseNumber, title, description, pricePerDay, numberOfGuests, numberOfBedrooms,
                numberOfBathrooms, numberOfBeds, publishedAt, isActive, host, accommodationType, null,
                null);
        logger.info("New Accommodation created  with the title: {} - without: parklocation and image list.", title);
    }

    public Accommodation(int id, String zipCode, String houseNumber, String title, String description,
                         double pricePerDay, int numberOfGuests, int numberOfBedrooms, int numberOfBathrooms,
                         int numberOfBeds, LocalDateTime publishedAt, Boolean isActive,
                         AccommodationType accommodationType) {
        this(id, zipCode, houseNumber, title, description, pricePerDay, numberOfGuests, numberOfBedrooms,
                numberOfBathrooms, numberOfBeds, publishedAt, isActive, null, accommodationType, null,
                null);
        logger.info("New Accommodation created  with the title: {} - without: host, parklocation and image list.", title);
    }

    // no args constructor
    public Accommodation() {
        super();
        this.id = 0; // placeholder - id is autogenerated in workbench
        this.publishedAt = LocalDateTime.now();
        logger.info("Instance of Accommodation created  with the title: {} - with a 'no args' constructor.", title);
    }

    // getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public String getHouseNumber() {
        return houseNumber;
    }

    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getPricePerDay() {
        return pricePerDay;
    }

    public void setPricePerDay(double pricePerDay) {
        this.pricePerDay = pricePerDay;
    }

    public int getNumberOfGuests() {
        return numberOfGuests;
    }

    public void setNumberOfGuests(int numberOfGuests) {
        this.numberOfGuests = numberOfGuests;
    }

    public int getNumberOfBedrooms() {
        return numberOfBedrooms;
    }

    public void setNumberOfBedrooms(int numberOfBedrooms) {
        this.numberOfBedrooms = numberOfBedrooms;
    }

    public int getNumberOfBathrooms() {
        return numberOfBathrooms;
    }

    public void setNumberOfBathrooms(int numberOfBathrooms) {
        this.numberOfBathrooms = numberOfBathrooms;
    }

    public int getNumberOfBeds() {
        return numberOfBeds;
    }

    public void setNumberOfBeds(int numberOfBeds) {
        this.numberOfBeds = numberOfBeds;
    }

    public LocalDateTime getPublishedAt() {
        return publishedAt;
    }

    public void setPublishedAt(LocalDateTime publishedAt) {
        this.publishedAt = publishedAt;
    }

    public Boolean getActive() {
        return isActive;
    }

    public void setActive(Boolean active) {
        isActive = active;
    }

    public AppUser getHost() {
        return host;
    }

    public void setHost(AppUser host) {
        this.host = host;
    }

    public AccommodationType getAccommodationType() {
        return accommodationType;
    }

    public void setAccommodationType(AccommodationType accommodationType) {
        this.accommodationType = accommodationType;
    }

    public ParkLocation getParkLocationId() {
        return parkLocationId;
    }

    public void setParkLocationId(ParkLocation parkLocationId) {
        this.parkLocationId = parkLocationId;
    }

    public List<Image> getImageList() {
        return imageList;
    }

    public void setImageList(List<Image> imageList) {
        this.imageList = imageList;
    }

    @Override
    public String toString() {
        return "Accommodation{" +
                "id=" + id +
                ", zipCode='" + zipCode + '\'' +
                ", houseNumber='" + houseNumber + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", pricePerDay=" + pricePerDay +
                ", numberOfGuests=" + numberOfGuests +
                ", numberOfBedrooms=" + numberOfBedrooms +
                ", numberOfBathrooms=" + numberOfBathrooms +
                ", numberOfBeds=" + numberOfBeds +
                ", publishedAt=" + publishedAt +
                ", isActive=" + isActive +
                ", host=" + host +
                ", accommodationType=" + accommodationType +
                ", parkLocationId=" + parkLocationId +
                ", imageList=" + imageList +
                '}';
    }

}
