package com.reisparadijs.reisparadijs.business.domain;

import jakarta.validation.constraints.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*********************************************
 * @Author Mirre Cicilia
 * @Studentennummer 500241293
 * @Project Accommodation.java
 * @Created 11 August Sunday 2024 - 16:56
 * @Korte beschrijving: De AccommodationType klasse vertegenwoordigt de blauwdruk van accommodatietype in het systeem.
 * Deze klasse heeft attributen zoals een id en een naam. De klasse biedt methoden om de kenmerken te beheren en een
 * leesbare weergave van een accommodatie type te geven. Deze klasse implementeert Comparable voor natuurlijke sortering
 * op de naam van het accommodatietype.
 **********************************************/
public class AccommodationType implements Comparable<AccommodationType> {

    private static final Logger logger = LoggerFactory.getLogger(AccommodationType.class);

    private int id;
    @NotNull(message = "Must be one of the following values: 'House', 'Apartment', 'GuestHouse' or 'Hotel'")
    private String name;

    public AccommodationType(String name) {
        super();
        this.id = 0; // placeholder - id is autogenerated in workbench
        this.name = name;
        logger.info("New AccommodationType created with the name: {}.", name);
    }

    public AccommodationType() {
        super();
        this.id = 0; // placeholder - id is autogenerated in workbench
        logger.info("Instance of AccommodationType created with the no args constructor.");
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // natural sorting: name
    @Override
    public int compareTo(AccommodationType otherAccommodationType) {
        return this.name.compareTo(otherAccommodationType.name);
    }

    @Override
    public String toString() {
        return "AccommodationType{" +
                "id=" + id +
                ", name='" + name + '\'' +
                '}';
    }

}
