
spring:
  profiles:
    active: dev
  application:
    name: Reisparadijs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: inforeisparadijs1@gmail.com
    password: uvrdhkacljofbolu
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

app:
  secret: c04nKbDFfJ2v0XSRtNKHQQq5Km3zMSZxla7paMSUzBOI/ORhgnTC7eJrqqEZQGKm
  jwt:
    token:
      expires-in: 3600000 #{60 * 60 * 1000} # 60 minutes in milliseconds
    refresh-token:
      expires-in: 86400000 #{24 * 60 * 60 * 1000} # 24 hours in milliseconds
    remember-me:
      expires-in: 604800000 #{24 * 60 * 60 * 1000 * 7} # 7 days in milliseconds
  registration:
    email:
      token:
        expires-in: 3600000 #{60 * 60 * 1000} # 60 minutes in milliseconds
    password:
      token:
        expires-in: 3600000 #{60 * 60 * 1000} # 60 minutes in milliseconds
  url: http://localhost:${server.port}
  frontend-url: http://localhost:${server.port}




